In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("loan_approval_data.csv")
df

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,NaN,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,NaN,Not Graduate,Male,Unemployed,No
996,997.0,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,Business,Urban,Graduate,Female,Government,No
997,998.0,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,Male,MNC,No
998,999.0,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,Male,Private,Yes
999,1000.0,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,NaN,Private,No

In [3]:
## Data Pre-Processing and EDA

df["Employment_Status"].unique() ## 4 -> Salaried    Self-employed    Contract    Unemployed
df["Marital_Status"].unique()    ## 2 -> Married    Single
df["Loan_Purpose"].unique()      ## 5 -> Personal    Car    Business    Home    Education
df["Property_Area"].unique()     ## 3 -> Urban    Semiurban    Rural
df["Education_Level"].unique()   ## 2 -> Not Graduate    Graduate
df["Gender"].unique()            ## 2 -> Female    Male
df["Employer_Category"].unique() ## 5 -> Private    Government    Unemployed    MNC    Business
df["Loan_Approved"].unique()     ## 2 -> No    Yes

array(['No', 'Yes', nan], dtype=object)

In [4]:
## Handling null values and Data Preprocesssing

c = ["Applicant_Income", "Coapplicant_Income", "Age", "Dependents", "Credit_Score", "Existing_Loans", "DTI_Ratio", "Savings", "Collateral_Value", "Loan_Amount", "Loan_Term"]

for col in c:
    df[col] = df[col].fillna(df[col].median())

columns = list(df.columns)
c2 = [col for col in columns if col not in c]
c2.remove('Applicant_ID')
c2.remove('Loan_Approved')

for col in c2:
    df[col] = df[col].fillna(df[col].mode()[0])

# df["Applicant_Income"] = df["Applicant_Income"].fillna(df["Applicant_Income"].median())
# df["Coapplicant_Income"] = df["Coapplicant_Income"].fillna(df["Coapplicant_Income"].median())
# df["Age"] = df["Age"].fillna(df["Age"].median())
# df["Dependents"] = df["Dependents"].fillna(df["Dependents"].median())
# df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].median())
df = df.drop(columns = ["Applicant_ID"])

df["Gender"] = df["Gender"].map({
    "Male":1,
    "Female":0
})

df["Loan_Approved"] = df["Loan_Approved"].map({
    "Yes" : 1,
    "No" : 0
})

df

,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,0,Private,0.0
1,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,48.0,Car,Semiurban,Graduate,1,Private,0.0
2,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,Business,Urban,Graduate,0,Government,1.0
3,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,0,Government,0.0
4,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,Urban,Graduate,1,Private,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10548.0,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,Urban,Not Graduate,1,Unemployed,0.0
996,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,9880.5,18361.0,22563.0,12.0,Business,Urban,Graduate,0,Government,0.0
997,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,1,MNC,0.0
998,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,1,Private,1.0
999,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,1,Private,0.0

In [5]:
## Train Test Split

untested_data = df[df["Loan_Approved"].isna()]

data = df.dropna()

X = data.drop(columns = ["Loan_Approved"])
y = data["Loan_Approved"]

## Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 18)

In [6]:
## One Hot Encoding
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown = "ignore")

X_train_numerical = X_train.drop(columns = c2)
X_test_numerical = X_test.drop(columns = c2)

X_train_encoded = encoder.fit_transform(X_train[c2]).toarray()
X_test_encoded = encoder.transform(X_test[c2]).toarray()

encoded_columns = encoder.get_feature_names_out(c2)

X_train_categorical = pd.DataFrame(
    X_train_encoded,
    columns = encoded_columns,
    index = X_train.index
)

X_test_categorical = pd.DataFrame(
    X_test_encoded,
    columns = encoded_columns,
    index = X_test.index
)

## Concatenation
X_train_encoded = pd.concat(
    [X_train_numerical, X_train_categorical],
    axis = 1
)

X_test_encoded = pd.concat(
    [X_test_numerical, X_test_categorical],
    axis = 1
)

In [7]:
## Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

In [8]:
## Model - kNN

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 19)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

In [9]:
## Evaluation

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy : {accuracy}    Precision : {precision}    Recall : {recall}    F1-score : {f1}")

Accuracy : 0.7578947368421053    Precision : 0.84    Recall : 0.3333333333333333    F1-score : 0.4772727272727273

In [10]:
## Fine Tuning the kNN model using different values of n_neighbors (k = 11 appears to be the best choice)

for k in range(1,32,2):
    model = KNeighborsClassifier(n_neighbors = k)
    model.fit(X_train_scaled, y_train)
    
    y_pred = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    
    print(f"For k = {k} ->  Accuracy : {accuracy}    Precision : {precision}    Recall : {recall}    F1-score : {f1}")

For k = 1 ->  Accuracy : 0.6789473684210526    Precision : 0.5151515151515151    Recall : 0.5396825396825397    F1-score : 0.5271317829457365
For k = 3 ->  Accuracy : 0.7368421052631579    Precision : 0.6101694915254238    Recall : 0.5714285714285714    F1-score : 0.5901639344262295
For k = 5 ->  Accuracy : 0.7421052631578947    Precision : 0.6458333333333334    Recall : 0.49206349206349204    F1-score : 0.5585585585585585
For k = 7 ->  Accuracy : 0.7526315789473684    Precision : 0.6818181818181818    Recall : 0.47619047619047616    F1-score : 0.5607476635514018
For k = 9 ->  Accuracy : 0.7631578947368421    Precision : 0.7142857142857143    Recall : 0.47619047619047616    F1-score : 0.5714285714285714
For k = 11 ->  Accuracy : 0.7736842105263158    Precision : 0.75    Recall : 0.47619047619047616    F1-score : 0.5825242718446602
For k = 13 ->  Accuracy : 0.7789473684210526    Precision : 0.8    Recall : 0.4444444444444444    F1-score : 0.5714285714285714
For k = 15 ->  Accuracy : 0.7736842105263158    Precision : 0.8125    Recall : 0.4126984126984127    F1-score : 0.5473684210526316
For k = 17 ->  Accuracy : 0.7684210526315789    Precision : 0.8064516129032258    Recall : 0.3968253968253968    F1-score : 0.5319148936170213
For k = 19 ->  Accuracy : 0.7578947368421053    Precision : 0.84    Recall : 0.3333333333333333    F1-score : 0.4772727272727273
For k = 21 ->  Accuracy : 0.7631578947368421    Precision : 0.9090909090909091    Recall : 0.31746031746031744    F1-score : 0.47058823529411764
For k = 23 ->  Accuracy : 0.7578947368421053    Precision : 0.8148148148148148    Recall : 0.3492063492063492    F1-score : 0.4888888888888889
For k = 25 ->  Accuracy : 0.7631578947368421    Precision : 0.8461538461538461    Recall : 0.3492063492063492    F1-score : 0.4943820224719101
For k = 27 ->  Accuracy : 0.7631578947368421    Precision : 0.8461538461538461    Recall : 0.3492063492063492    F1-score : 0.4943820224719101
For k = 29 ->  Accuracy : 0.7421052631578947    Precision : 0.7916666666666666    Recall : 0.30158730158730157    F1-score : 0.4367816091954023
For k = 31 ->  Accuracy : 0.7368421052631579    Precision : 0.8421052631578947    Recall : 0.25396825396825395    F1-score : 0.3902439024390244

In [11]:
## Model - Logistic Regression

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"For Logistic Regression ->  Accuracy : {accuracy}    Precision : {precision}    Recall : {recall}    F1-score : {f1}")

For Logistic Regression ->  Accuracy : 0.8947368421052632    Precision : 0.864406779661017    Recall : 0.8095238095238095    F1-score : 0.8360655737704918

In [12]:
## Model - Gaussian NB

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"For Gaussian Naive Bayes ->  Accuracy : {accuracy}    Precision : {precision}    Recall : {recall}    F1-score : {f1}")

For Gaussian Naive Bayes ->  Accuracy : 0.8789473684210526    Precision : 0.8571428571428571    Recall : 0.7619047619047619    F1-score : 0.8067226890756303